"""Import the 鋒兄宇宙 song library from the goldshoot0720/Effects repo for the PVs.

Reads Effects/data/song/<id>.js (timed lyrics, sections, baked audio analysis),
copies Effects/audio/<id>.mp3 to songs/, and writes songs/songs.js with
lyrics, sections, BPM / first beat and two 30 fps envelopes (base64 bytes):
  low  - bass bands (kick / camera hits)
  voc  - mid bands (drives the singers' mouths)

Run:  python3 tools/import-songs.py [/path/to/Effects]
"""
import base64
import json
import os
import re
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IDS = ['s023', 's024', 's026', 's027', 's028', 's029', 's062', 's101', 's102']


def load(effects, sid):
    text = open(os.path.join(effects, 'data', 'song', sid + '.js'), encoding='utf-8').read()
    return json.loads(re.search(r'\]=(\{.*\})\s*;?\s*$', text, re.S).group(1))


def envelopes(a):
    n, k = a['frames'], a['bandCount']
    bands = base64.b64decode(a['bands'])
    assert len(bands) >= n * k, 'unexpected band layout'

    def env(lo, hi):
        out = bytearray(n)
        for f in range(n):
            row = bands[f * k + lo:f * k + hi]
            out[f] = sum(row) // len(row)
        peak = sorted(out)[int(n * 0.98)] or 1
        return base64.b64encode(bytes(min(255, v * 230 // peak) for v in out)).decode()

    return env(0, 2), env(3, 8)


def main(effects):
    os.makedirs(os.path.join(ROOT, 'songs'), exist_ok=True)
    out = []
    for sid in IDS:
        d = load(effects, sid)
        a = d['analysis']
        low, voc = envelopes(a)
        lines = [{'t': l['t'], 'd': l.get('d', 2), 'text': l['text'], 'sec': l['sec']} for l in d['lines']]
        # lines sharing a timestamp would never be seen; spread them out
        for i in range(1, len(lines)):
            if lines[i]['t'] <= lines[i - 1]['t']:
                nxt = lines[i + 1]['t'] if i + 1 < len(lines) else lines[i - 1]['t'] + 2
                lines[i]['t'] = round((lines[i - 1]['t'] + nxt) / 2, 2)
        shutil.copyfile(os.path.join(effects, 'audio', sid + '.mp3'), os.path.join(ROOT, 'songs', sid + '.mp3'))
        out.append({
            'id': sid, 'title': d['title'], 'cast': d['cast'], 'tagline': d['tagline'], 'theme': d['theme'],
            'audio': f'songs/{sid}.mp3', 'dur': a['duration'], 'bpm': a['bpm'], 'beat0': a['beat0'],
            'fps': a['bandFps'], 'low': low, 'voc': voc,
            'sections': [{'kind': s['kind'], 'start': s['start'], 'end': s['end']} for s in d['sections']],
            'lines': lines,
        })
        print(sid, d['title'], len(lines), 'lines', f"{a['duration']:.0f}s", f"{a['bpm']:.1f} BPM")
    with open(os.path.join(ROOT, 'songs', 'songs.js'), 'w', encoding='utf-8') as f:
        f.write('// Generated by tools/import-songs.py from goldshoot0720/Effects. Do not edit by hand.\n')
        f.write('export const SONGS = ')
        json.dump(out, f, ensure_ascii=False, separators=(',', ':'))
        f.write(';\n')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, '..', 'Effects'))
